name: Run Test Cases

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "0 0 * * 1,4"  # Runs at midnight UTC every Monday and Thursday

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build and test with Maven
        run: mvn surefire:test
